### ISSUE TITLE
ArgumentException: method return type is incompatible

### ISSUE THREAD

**Issue by idontknowbrh** [byvar/ubi-canvas#13]
ArgumentException: method return type is incompatible
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEditor.HostView.CreateDelegate (System.String methodName) (at <a5bc71bb4d98498aba1f868b89d20d47>:0)
UnityEditor.HostView.CreateDelegates () (at <a5bc71bb4d98498aba1f868b89d20d47>:0)
UnityEditor.HostView.OnEnable () (at <a5bc71bb4d98498aba1f868b89d20d47>:0)
UnityEditor.DockArea.OnEnable () (at <a5bc71bb4d98498aba1f868b8

**Comment by RayCarrot** [comment]
Hi! The issue has been fixed now.
