### ISSUE TITLE
Some general questions about the UbiArt Framework/Rayman Legends logic #2.

### ISSUE THREAD

**Issue by GitLordv** [byvar/ubi-canvas#24]
Hi! 

There are quite a lot of questions so I apologise in advance for the time spent.
Also not sure if I should create new issue's just for questions... but I didn't find another place. :)

1) I saw a platform editing tool in Ubi-Canvas (the one that switches the texture depending on the tilt angle) exactly like the one presented by UbiArt developers at GDC 2018.
But when I moved the control points, and saved the ipk patch in the game there was no change or rearrangement of the platform and its collision....
Is this functionality even present in Ubi-Canvas or was all the platform geometry data baked in when the game was built?
This is the tool I have in mind:

    [![Ubi-Canvas-Editor.png](https://i.postimg.cc/FsX2cmr1/Ubi-Canvas-Editor.png)](https://postimg.cc/pykGbwnt)

2) Is there any way to enable the display of tag icons directly in the RL game? After all, if in Ubi-Canvas we can observe the icons... then the information about their position is in the .exe file of the game or Ubi-Canvas calculates it itself? 

3) Where do I need to change the "Instruction Set" fields? In TweenComponent or TweenComponent_Template scripts to override the "tweening" logic of the object? And is it possible to add a TweenComponent itself for static Frize?

4) Will it be possible in the future to copy objects on Ctrl + C; Ctrl + V? Right now it causes an error: "NullReferenceException: Object reference not set to an instance of an object" from Unity. This could be circumvented by creating .act for any individual objects, except that it seems to be impossible at the moment for simple static frize.

5) Can you describe why in Scene view all frontlight_fill objects look like a normal colour instead of multiply mode, which prevents the selection of objects on the background, but in Game view the light looks correct.

    [![image.png](https://i.postimg.cc/c43MQ67Y/image.png)](https://postimg.cc/1f9qSmj5)

6) And the last one... if I can understand what different tag icons do, then I what is the purpose of the bounce_target icon type (black and yellow icon)? Is it some sort of logical target for the object? But there is a trajectory_node right? 
In almost every RL level at the very start there are 4-5 instances of bounce_target arranged in a row, but what are they for?

    <a href="url"><img src="https://i.postimg.cc/J4XvGrGY/image.png" align="left" height="361" width="566" ></a>

**Comment by RayCarrot** [comment]
Hi! Would you be interested in joining the Rayman Modding Discord server? I'm thinking it might be easier asking questions there ^^. I don't want to post an invite here, but feel free to message me on Discord and I can send an invite there. I have the same username there, but all lowercase.
