### ISSUE TITLE
Its not issue related but i need some help

### ISSUE THREAD

**Issue by baguettesenpaii** [byvar/ubi-canvas#9]
Hey! I love rayman legends visuals and atmosphere so i wanted to make some wallpapers for myself using this level editor. I got to the part where i have to add the games directory. Does that mean the game folder that i installed for rayman legends? Because i choosed that, then no scene file appeared in unity at all, even after 10 minutes of waiting.

**Comment by RayCarrot** [comment]
The folder path you set should be to the extracted data, so not to the install directory. For Legends you'll need to extract the Bundle_PC.ipk file and then set the path to the extracted folder. You can extract it either using QuickBMS (using this [script](https://drive.google.com/file/d/1dSBDAHnmLte2crw3DagYiXSihPTOg4P8/view?usp=sharing)) or the Rayman Control Panel (using the Archive Explorer utility).

**Comment by baguettesenpaii** [comment]
Worked perfectly, thank you ^^
